version: '3'

volumes:
  nexus-data:

services:
  nexus:
    image: docker.io/sonatype/nexus3:${TAG:-latest}
    container_name: nexus
    restart: unless-stopped
    network_mode: bridge
    hostname: nexus
    ports:
      - 8081:8081
    volumes:
      - "nexus-data:/nexus-data"
