version: "3"

volumes:
  work:

services:
  scipy-jupyter:
    image: docker.io/jupyter/scipy-notebook:${TAG:-python-3.10}
    container_name: jupyter
    user: root
    restart: unless-stopped
    network_mode: bridge
    hostname: jupyter
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=easytoken
      - GRANT_SUDO=yes
    volumes:
      - work:/home/jovyan/work
